### ISSUE TITLE
please read

### ISSUE THREAD

**Issue by raikenz** [PringlePot/LCWebsocket#3]
hey pringles, can u please tell me how do i download this i really need it

**Comment by PringlePot** [comment]
hey dm me on discord, also im not sure if this still works since I havent touched it in a while

**Comment by PringlePot** [comment]
Its also really a pain in the ass to set it up right now, since microsoft account authentication is difficult.

**Comment by raikenz** [comment]
hey but i dont really know ur discord

**Comment by PringlePot** [comment]
oh, its `Pringles#8249`
